---
title: "Case-control analysis script ECC Risks factors"
output: html_notebook
---

# General setup and packages

```{r}
knitr::opts_chunk$set(
  fig.width = 12,
  fig.height = 8,
  fig.path = 'Figs/',
  echo = FALSE,
  include= TRUE,  # for the chunks to be displayed
  warning = FALSE,
  message = FALSE,
  out.width = "75%"
)# Use include=TRUE for the chunks to be displayed
```

```{r}
pacman::p_load(tidyverse, 
               visdat, # for NAs
               table1, 
               janitor,  # for data cleaning
               sjPlot,   # for model vis
               gtsummary, # for summary tables
               performance # for regression diagnostic check
)
```

# Dataset

```{r}
ecc <- read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vRaanB0FUyB-NrIJpC_OpxZ2E6h3gsZ5sM65E-5PEvXxew2UGfBWXAU38jGww_GklQCDWyDJ63o-KNc/pub?gid=0&single=true&output=csv")
```

## Data cleaning

```{r}
ecc <- ecc %>% 
  filter(Age < 6) %>% 
  janitor::clean_names() %>% 
  janitor::remove_empty(which = c("rows", "cols")) %>% 
  select(-c(code, 
            syrup, 
            examination_date, 
            birth_date))
```

# Exploratory Data Analysis

```{r}
glimpse(ecc)
```

Cases and controls

```{r}
table(ecc$ecc)
```

## Table 1

```{r}
ecc %>%
  
  select(age, gender, ecc) %>%
  gtsummary::tbl_summary(
    by = gender,
    type = "age" ~ "continuous2", 
    statistic = all_continuous() ~ "{mean} ({sd})"
  )
```


```{r}
ecc <- ecc %>% 
  mutate(ecc2 = case_when(
    ecc == "Yes" ~ "1", 
    TRUE ~ "0"
  )) %>% 
  mutate(ecc2 = as.integer(ecc2)) 
```


```{r}
ecc %>% 
  janitor::tabyl(ecc2) %>% 
  janitor::adorn_pct_formatting()
```

```{r}
ecc %>% 
  group_by(ecc) %>% 
  summarize(mean(age), sd(age))
```


# Risk factors

ecc for modelling

```{r}
m1 <-
  glm(
    ecc2 ~ age + gender,
    data = ecc,
    family = binomial()
  )
```

# Risk Model
